---
- name: Download Rustup installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: '0755'

- name: Install Rustup
  ansible.builtin.shell: "/tmp/rustup-init.sh -y"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

- name: Remove Rustup installer
  ansible.builtin.file:
    path: /tmp/rustup-init.sh
    state: absent

- name: Install bat with Cargo
  command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install bat"

# - name: Install legba with Cargo
#   command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install legba"
