---
- name: Download Ollama install script
  ansible.builtin.get_url:
    url: https://ollama.com/install.sh
    dest: /tmp/ollama-install.sh
    mode: '0755'

- name: Install Ollama
  ansible.builtin.shell: "/tmp/ollama-install.sh"
  args:
    creates: /usr/local/bin/ollama

- name: Remove Ollama installer
  ansible.builtin.file:
    path: /tmp/ollama-install.sh
    state: absent

- name: Pull Ollama Mistral model
  ansible.builtin.shell: "ollama pull mistral"
