---
# Deploy hardened user.js configuration

- name: Find Firefox profile directories
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.mozilla/firefox"
    file_type: directory
    patterns: "*.default*"
  register: firefox_profiles

- name: Create Firefox profiles backup directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.mozilla/firefox/profile_backups"
    state: directory
    mode: '0700'
  when: firefox_profiles.matched > 0

- name: Backup existing Firefox profiles
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.mozilla/firefox/profile_backups/{{ item.path | basename }}_{{ ansible_date_time.date }}"
    remote_src: yes
  with_items: "{{ firefox_profiles.files }}"
  when: firefox_profiles.matched > 0

- name: Deploy hardened user.js to each Firefox profile
  ansible.builtin.template:
    src: user.js.j2
    dest: "{{ item.path }}/user.js"
    mode: '0644'
    backup: yes
  with_items: "{{ firefox_profiles.files }}"
  when: firefox_profiles.matched > 0
  register: user_js_deployed

- name: Set fact about user.js deployment
  ansible.builtin.set_fact:
    user_js_deployed: "{{ user_js_deployed is changed }}" 