---
- include_tasks: "apt.yml"
- include_tasks: "xfce.yml"
  when: install_desktop == 'xfce'
- include_tasks: "i3.yml"
  when: install_desktop == 'i3'
- include_tasks: "regolith.yml"
  when: install_desktop == 'regolith'
