---
- name: Install Alacritty with APT
  apt:
    name: alacritty
    state: present
  become: true
  
- name: Set Alacritty as default terminal emulator
  command: update-alternatives --set x-terminal-emulator /usr/bin/alacritty
  become: true

- name: "Copying Burp Script"
  copy:
    src: files/alacritty.toml
    dest: /etc/xdg/alacritty/alacritty.toml
    mode: 0644
  become: true
