---
- name: Check if VM is VMware
  set_fact:
    is_vmware: "{{ ansible_virtualization_type == 'VMware' }}"

- name: Copy file if VM is VMware
  copy:
    src: "{{ role_path }}/files/vmware.txt"
    dest: "{{ ansible_env.HOME }}/VMWare_shared_folder.txt"
  when: is_vmware
