[colors.bright]
black = "0x198388"
blue = "0x277FFF"
cyan = "0x05A1F7"
green = "0x47D4B9"
magenta = "0x962AC3"
red = "0xEC0101"
white = "0xFFFFFF"
yellow = "0xFF8A18"

[colors.normal]
black = "0x1F2229"
blue = "0x367BF0"
cyan = "0x49AEE6"
green = "0x5EBDAB"
magenta = "0x9755B3"
red = "0xD41919"
white = "0xE6E6E6"
yellow = "0xFEA44C"

[colors.primary]
background = "0x23252e"
foreground = "0xFFFFFF"

[font]
size = 10

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-c", "alacritty --working-directory=$(pwd)"]
program = "/bin/sh"

[window.padding]
x = 5
y = 5
